name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install go
        run: |
          sudo apt update
          sudo apt install golang

      - name: Build test cli
        run: make build-test-cli

      - name: Run tests
        run: ./testing/test-cli
