name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Set Warsaw timezone
        run: sudo timedatectl set-timezone Europe/Warsaw

      - name: Install go
        run: |
          sudo apt update
          sudo apt install golang

      - name: Build test cli
        run: make build-test-cli

      - name: Build test daemon
        run: make build-test-daemon

      - name: Run tests
        run: sudo ./run-tests
